// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RefugioMascotas;

#nullable disable

namespace RefugioMascotas.Migrations
{
    [DbContext(typeof(RefugioDbContext))]
    [Migration("20260819031015_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("RefugioMascotas.Models.Cuidador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cuidadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Maria Lopez",
                            Turno = "Manana"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Carlos Perez",
                            Turno = "Tarde"
                        });
                });

            modelBuilder.Entity("RefugioMascotas.Models.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CuidadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnTratamiento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CuidadorId");

                    b.ToTable("Mascotas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CuidadorId = 1,
                            Edad = 5,
                            EnTratamiento = false,
                            Especie = "Perro",
                            Nombre = "Toby"
                        },
                        new
                        {
                            Id = 2,
                            CuidadorId = 2,
                            Edad = 3,
                            EnTratamiento = true,
                            Especie = "Gato",
                            Nombre = "Michi"
                        });
                });

            modelBuilder.Entity("RefugioMascotas.Models.Mascota", b =>
                {
                    b.HasOne("RefugioMascotas.Models.Cuidador", "Cuidador")
                        .WithMany("Mascotas")
                        .HasForeignKey("CuidadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuidador");
                });

            modelBuilder.Entity("RefugioMascotas.Models.Cuidador", b =>
                {
                    b.Navigation("Mascotas");
                });
#pragma warning restore 612, 618
        }
    }
}
